---
- name: confirm java is executable
  ansible.builtin.command: /usr/local/openjdk-jre/bin/java -version
  register: openjdk_jre_test_output
- name: java -version
  ansible.builtin.debug:
    msg: '{{ openjdk_jre_test_output.stderr }}'
