---
- name: confirm javac is executable
  ansible.builtin.command: /usr/local/openjdk-jdk/bin/javac -version
  register: openjdk_jdk_test_output
- name: javac -version (stdout)
  ansible.builtin.debug:
    msg: '{{ openjdk_jdk_test_output.stdout }}'
- name: javac -version (stderr)
  ansible.builtin.debug:
    msg: '{{ openjdk_jdk_test_output.stderr }}'
- ansible.builtin.import_tasks: test-jre-exe.yml
