---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      openjdk_app: jre
  tasks:
    - import_tasks: test-jre-exe.yml
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      openjdk_app: jdk
  tasks:
    - import_tasks: test-jdk-exe.yml
